services:
        app:
            build:
                context: .
                dockerfile: Dockerfile
            container_name: laravel-app
            volumes:
                - .:/var/www/html
            ports:
                - "8000:80"
            networks:
                - laravel_net

        db:
            image: mysql:8.0
            container_name: laravel-db
            environment:
                MYSQL_ROOT_PASSWORD: root_password
                MYSQL_DATABASE: laravel_db
                MYSQL_USER: laravel_user
                MYSQL_PASSWORD: laravel_password
            volumes:
                - db_data:/var/lib/mysql
            ports:
                - "3306:3306"
            networks:
                - laravel_net

        phpmyadmin:
            image: phpmyadmin/phpmyadmin
            container_name: laravel-pma
            ports:
                - "8080:80"
            environment:
                PMA_HOST: db
                PMA_USER: laravel_user
                PMA_PASSWORD: laravel_password
            depends_on:
                - db
            networks:
                - laravel_net

networks:
    laravel_net:
        driver: bridge

volumes:
    db_data:
        driver: local
